config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de/ do
    root to: 'items#index'

    # ActiveAdmin routes
    ActiveAdmin.routes(self)
    #

    # Sidekiq
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    #

    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

    # Simple resources
    resources :cart_items, only: [:create]
    resources :carts, only: [:edit, :update]
    resources :deliveries, only: [:edit, :update, :index, :show]
    #

    post "order_items/:id/add_to_cart", to: "order_items#add_to_cart", as: "add_to_cart_order_item"

    # Complex resources
    resources :recipes, only: [:index, :show, :new, :create] do
      collection do
        post ":id/toggle_like", to: "recipes#toggle_like", as: :toggle_like
        post ":id/add_to_cart", to: "recipes#add_to_cart", as: :add_to_cart
      end
    end

    resources :items, only: [:index, :show] do
      collection do
        get "autocomplete"
      end
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        get :receipt, action: :receipt
        post :add_to_cart, action: :add_to_cart
      end
    end
    #

    namespace :stripe do
      # stripe_event gem Engine
      mount StripeEvent::Engine, at: '/webhook', as: :event
      #

      get "payment_intents/:id/confirm", to: "payment_intents#confirm", as: :payment_intents_confirm
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :orders, only: [:show] do
          collection do
            post "breakdown"
          end
        end

        post "users/:id/update_driver_coordinates", to: "users#update_driver_coordinates", as: :update_driver_coordinates

        resources :deliveries, only: [:update]
        resources :cart_items, only: [:update, :destroy]
      end
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # cacheable_strategy: :update_columns prevents votes from changing the recipe's updated_at column
	acts_as_votable cacheable_strategy: :update_columns

	has_rich_text :information

	has_many_attached :images

  belongs_to :user, optional: true

  has_many :recipe_items, inverse_of: :recipe

  default_scope { where(public: true) }

  validates_presence_of :name

  accepts_nested_attributes_for :recipe_items, reject_if: :all_blank, allow_destroy: true

  def add_to_cart(cart)
  	recipe_items.each { |recipe_item| cart.add_unit(recipe_item.unit, recipe_item.quantity) }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to recipes_path
		else
			render :new
		end
	end

	def toggle_like
		@recipe = Recipe.find(params[:id])

		current_user.toggle_like(@recipe)
	end

	def add_to_cart
		@recipe = Recipe.find(params[:id])

		@recipe.add_to_cart(current_user.cart)
	end

	private

	def recipe_params
		params.require(:recipe).permit(:name, :description, :public, :information, images: [], recipe_items_attributes: [:quantity, :item_id])
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<div class="card" id="recipe_<%= recipe.id %>">
	<% if recipe.images.attached? %>
		<%= image_tag recipe.images.first, class: "card-img-top", alt: recipe.name %>
	<% end %>

  <div class="card-body">
    <h5 class="card-title"><%= recipe.name %></h5>
    <p class="card-text"><%= recipe.get_likes.length %> likes</p>

    <%= link_to toggle_like_recipes_path(id: recipe.id), method: :post, remote: true, class: ["btn", current_user.liked?(recipe) ? "btn-success" : "btn-primary"] do %>
    	<%= fa_icon "thumbs-up" %>
    <% end %>

    <%= link_to "View recipe", recipe_path(id: recipe.id), class: "btn btn-primary" %>
  </div>
</div>

app/views/recipes/_recipe_item_fields.html.erb
<%= f.input :item_id, collection: Item.all.map { |item| [item.name, item.id] } %>
<%= f.input :quantity %>

app/views/recipes/add_to_cart.js.erb
$("#navbar").replaceWith("<%= j render 'layouts/navbar' %>") 

app/views/recipes/index.html.erb
<div class="container">
	<li class="list-group-item">
		<%= link_to "Create a recipe", new_recipe_path, class: "btn btn-success" %>
	</li>

	<div class="row">
		<% @recipes.each do |recipe| %>
			<div class="col-3">
				<%= render 'recipe', recipe: recipe %>
			</div>
		<% end %>
	</div>
</div>

app/views/recipes/like.js.erb
$("#recipe_<%= @recipe.id %>").replaceWith("<%= j render 'recipes/recipe', recipe: @recipe %>")

app/views/recipes/new.html.erb
<%= simple_form_for(@recipe) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.rich_text_area :information %>
	<%= f.input :public %>
	<%= f.file_field :images, multiple: true %>

	<div id="recipe_items">
		<%= f.simple_fields_for :recipe_items do |recipe_item| %>
			<%= render 'recipe_item_fields', f: recipe_item %>
		<% end %>
		
		<div class='links'>
      <%= link_to_add_association 'add ingredient', f, :recipe_items %>
    </div>
	</div>

	<%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h4><%= @recipe.name %></h4>
<p><%= @recipe.get_likes.length %> likes</p>
<p><%= @recipe.description %></p>

<h5>Ingredients</h5>

<ul>
	<% @recipe.recipe_items.each do |recipe_item| %>
		<li>
			<p>
				<%= recipe_item.quantity %>g of <%= recipe_item.item.name %>
			</p>
		</li>
	<% end %>
</ul>

<h5>Information</h5>

<%= @recipe.information %>

<%= link_to "Add to cart", add_to_cart_recipes_path(id: @recipe.id), method: :post, remote: true, class: "btn btn-success" %>

app/views/recipes/toggle_like.js.erb
$("#recipe_<%= @recipe.id %>").replaceWith("<%= j render 'recipes/recipe', recipe: @recipe %>") 

app/views/recipes/vote_for.js.erb
$("#recipe_<%= @recipe.id %>").replaceWith("<%= j render 'recipes/recipe', recipe: @recipe %>")