config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de/ do
    root to: 'items#index'

    # ActiveAdmin routes
    ActiveAdmin.routes(self)
    #

    # Sidekiq
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    #

    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

    # Simple resources
    resources :cart_items, only: [:create]
    resources :carts, only: [:edit, :update]
    resources :deliveries, only: [:edit, :update, :index, :show]
    #

    post "order_items/:id/add_to_cart", to: "order_items#add_to_cart", as: "add_to_cart_order_item"

    # Complex resources
    resources :recipes, only: [:index, :show, :new, :create] do
      collection do
        post ":id/toggle_like", to: "recipes#toggle_like", as: :toggle_like
        post ":id/add_to_cart", to: "recipes#add_to_cart", as: :add_to_cart
      end
    end

    resources :items, only: [:index, :show] do
      collection do
        get "autocomplete"
      end
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        get :receipt, action: :receipt
        post :add_to_cart, action: :add_to_cart
      end
    end
    #

    namespace :stripe do
      # stripe_event gem Engine
      mount StripeEvent::Engine, at: '/webhook', as: :event
      #

      get "payment_intents/:id/confirm", to: "payment_intents#confirm", as: :payment_intents_confirm
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :orders, only: [:show] do
          collection do
            post "breakdown"
          end
        end

        post "users/:id/update_driver_coordinates", to: "users#update_driver_coordinates", as: :update_driver_coordinates

        resources :deliveries, only: [:update]
        resources :cart_items, only: [:update, :destroy]
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true

  has_many :cart_items, dependent: :destroy, inverse_of: :cart

  accepts_nested_attributes_for :cart_items, reject_if: :all_blank, allow_destroy: true

  def add_cart_item(cart_item)
    add_unit(cart_item.unit, cart_item.quantity)
  end

  def add_unit(unit, amount = 1)
  	cart_item = cart_items.find { |cart_item| cart_item.unit == unit }

  	if cart_item
  		cart_item.add(amount)
  	else
  		CartItem.create(unit_id: unit.id, cart_id: id, quantity: amount)
  	end
  end

  def clear
  	cart_items.destroy_all
  end

  def find_cart_item(item)
  	cart_items.find { |cart_item| cart_item.item_id == item.id }
  end

  def total
    # Converted to cents and back to money to ensure no rounding disrepencies
    cart_items.sum { |cart_item| cart_item.total.to_cents }.to_money
  end

  def empty?
    cart_items.empty?
  end

  def to_order_items
    cart_items.map(&:to_order_item)
  end

  def count
    cart_items.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:edit, :update]

	def edit
		@cart = Cart.find(params[:id])
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<%= simple_form_for cart_item, url: api_v1_cart_item_path(id: cart_item.id), html: { class: "cart-item-partial" }, data: { controller: 'cart-item', action: 'cart-item#submitForm', target: 'cart-item.form', 'cart-item-price': cart_item.unit.price, 'cart-item-id': cart_item.id } do |f| %>
	<li class="list-group-item nested-fields pr-2 pl-0">
		<div class="d-flex align-items-center">
			<%= link_to 'cart_item/destroy', class: 'text-danger pr-2', style: "font-size: 20px;", data: { action: 'cart-item#destroyItem' } do %>
				<%= fa_icon 'minus-circle' %>
			<% end %>

			<% if cart_item.item.main_image.attached? %>
				<%= image_tag cart_item.item.main_image, style: "width: 80px;" %>
			<% end %>

			<div class="pl-4 pr-3" style="width: 280px;">
				<p class="mb-0">
					<%= cart_item.item.name %>
				</p>

				<div class="input-group">
				  <%= f.input_field :quantity, disabled: true, class: "form-control", data: { target: "cart-item.input", action: "input->cart-item#quantityChange" } %>

				  <div class="input-group-append" data-target="cart-item.buttonDiv">
				    <button class="btn btn-outline-primary" type="button" data-action="cart-item#editButton">
				    	<%= fa_icon 'pen' %>
				    </button>
				  </div>
				</div>

				<p class="mb-0 ml-1 text-muted" style="font-size: 12px;">
					Quantity in <%= cart_item.unit.name.pluralize %>
				</p>
			</div>

			<p class="mb-0 mt-2 text-right flex-grow-1" data-target="cart-item.price">
				<%= number_to_currency(cart_item.total) %>
			</p>
		</div>
	</li>
<% end %>

app/views/carts/_edit_sidebar.html.erb
<div class="h-100 d-flex flex-column h-100">
	<div class="p-3 d-flex justify-content-between align-items-center" style="background: rgba(0, 0, 0, 0.02);">
		<h4 class="m-0 font-weight-light">
			Max's Shopping Cart
		</h4>

		<button class="btn btn-outline-success" data-dismiss="sidebar">
			<%= fa_icon 'times' %>

			Close
		</button>
	</div>

	<% if @cart.count.positive? %>
		<div class="container flex-grow-1 overflow-auto">
		  <ul class="list-group list-group-flush">
		    <% @cart.cart_items.each do |cart_item| %>
		      <%= render 'cart_item', cart_item: cart_item %>
		    <% end %>
		  </ul>
		</div>

		<div class="p-2 border-top">
			<%= link_to new_order_path, id: "checkout_button", class: "btn btn-success btn-lg btn-block position-relative" do %>
				Checkout

				<div class="position-absolute" id="checkout_button_total" style="background: #218838; right: 5px; bottom: 3px; padding: 0.3rem; border-radius: 4px;">
					<%= number_to_currency(@cart.total) %>
				</div>
			<% end %>
		</div>
	<% else %>
		<p class="text-center my-auto px-5" style="font-size: 25px;">
			Your cart is currently empty
		</p>
	<% end %>
</div>

app/views/carts/edit.js.erb
sidebar.show("<%= j render 'carts/edit_sidebar' %>")