config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de/ do
    root to: 'items#index'

    # ActiveAdmin routes
    ActiveAdmin.routes(self)
    #

    # Sidekiq
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    #

    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

    # Simple resources
    resources :cart_items, only: [:create]
    resources :carts, only: [:edit, :update]
    resources :deliveries, only: [:edit, :update, :index, :show]
    #

    post "order_items/:id/add_to_cart", to: "order_items#add_to_cart", as: "add_to_cart_order_item"

    # Complex resources
    resources :recipes, only: [:index, :show, :new, :create] do
      collection do
        post ":id/toggle_like", to: "recipes#toggle_like", as: :toggle_like
        post ":id/add_to_cart", to: "recipes#add_to_cart", as: :add_to_cart
      end
    end

    resources :items, only: [:index, :show] do
      collection do
        get "autocomplete"
      end
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        get :receipt, action: :receipt
        post :add_to_cart, action: :add_to_cart
      end
    end
    #

    namespace :stripe do
      # stripe_event gem Engine
      mount StripeEvent::Engine, at: '/webhook', as: :event
      #

      get "payment_intents/:id/confirm", to: "payment_intents#confirm", as: :payment_intents_confirm
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :orders, only: [:show] do
          collection do
            post "breakdown"
          end
        end

        post "users/:id/update_driver_coordinates", to: "users#update_driver_coordinates", as: :update_driver_coordinates

        resources :deliveries, only: [:update]
        resources :cart_items, only: [:update, :destroy]
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
	$tags = [
		"gluten-free",
		"vegetarian",
		"vegan",
		"dairy-free",
		"organic"
	]

	include PgSearch::Model

	pg_search_scope :search,
	against: {
		name: 'A',
		description: 'B'
	},
	using: {
		tsearch: { 
			prefix: true,
			dictionary: "english"
		},
		trigram: {
			only: [:name]
		}
	}

	acts_as_taggable_on :tags

	has_one_attached :main_image
	has_many_attached :images

	has_many :item_container_types, dependent: :destroy
	has_many :stocks, dependent: :destroy
	has_many :units, dependent: :nullify

	has_many :container_types, through: :item_container_types

	validates_presence_of :name, :price

	before_save :generate_default_units, if: Proc.new { |item| item.units.empty? }

	def base_unit
		units.find(&:base?)
	end

	def default_unit
		units.find(&:default?)
	end

	def stock
		stocks.sum(&:balance)
	end

	def image_count
		images.count + (main_image.attached? ? 1 : 0)
	end

	def display_price
		display_quantity * default_unit.price
	end

	def display_unit
		if display_quantity > 1
			"#{display_quantity.to_s} #{default_unit.name.pluralize}"
		else
			default_unit.name
		end
	end

	private

	def generate_default_units
		self.units = [
			Unit.new(name: "gram", base_units: 1),
			Unit.new(name: "kg", base_units: 1000, default: true)
		]
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show, :autocomplete]

  def index
    @order_options = [
      ["Relevance", "relevance"],
      ["Price Ascending", "price_asc"],
      ["Price Descending", "price_desc"],
      ["Alphabetical", "alphabetical"]
    ]

    @items = Item.all

    search_items if params[:search].present?
    filter_items if params[:filter].present?
    order_items if params[:order].present?

    @item_count = @items.count # Neccessary to count before pagination when .paginate is called on array

  	@items = @items.paginate(page: params[:page], per_page: 24)
  end

  def show
  	@item = Item.find(params[:id])
  end

  def autocomplete
    @items = Item.all

  	search_items if params[:search].present?

    @items = @items.limit(5) unless @items.empty?

  	render layout: false
  end

  private

  def order_items
    order = params[:order]

    case order
    when "relevance"
      # Fancy order
    when "price_asc"
      @items = @items.sort_by(&:display_price)
    when "price_desc"
      @items = @items.sort_by(&:display_price).reverse
    when "alphabetical"
      @items.reorder!(name: :asc)
    end
  end

  def search_items
    @items = @items.search(params[:search])
  end

  def filter_items
    params[:filter].each do |filter|
      @items = @items.tagged_with(filter) unless filter.blank?
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div class="card border-0 h-100 item-card" id="item_<%= item.id %>">
  <%= link_to item_path(id: item.id), remote: true, data: { toggle: "modal", target: "#modal-window" } do %>
    <% if item.main_image.attached? %>
      <%= image_tag item.main_image, class: "card-img-top", alt: item.name %>
    <% end %>

    <div class="card-body text-center">
      <h5 class="card-title text-secondary font-weight-normal">
        <%= item.name %>
      </h5>

      <p class="card-text text-dark mb-0" style="font-weight: 600">
        <%= number_to_currency(item.display_price) %>

        <span class="text-muted">
          <%= " / " + item.display_unit %>
        </span>
      </p>

      <% current_cart.cart_items.where(unit: item.units).sort_by { |ci| ci.unit.name.length }.reverse.each do |cart_item| %>
        <small class="text-muted d-block" id="cart_item_display_<%= cart_item.id %>">
          <%= t("unit.#{cart_item.unit.name}", count: cart_item.quantity) %> in cart
        </small>
      <% end %>
    </div>

    <%= fa_icon 'plus-square', type: :regular, class: "text-success" %>
  <% end %>
</div>

app/views/items/_show_modal.html.erb
<div class="modal-body">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>

	<div class="container-fluid pt-4">
		<div class="row align-items-center">
			<div class="col-12 col-lg-6 text-center">
				<% if @item.image_count.positive? %>
					<% if @item.image_count > 1 %>
						<!-- Slider main container -->
						<div class="swiper-container" data-controller="swiper">
					    <!-- Additional required wrapper -->
					    <div class="swiper-wrapper align-items-center">
				        <!-- Slides -->
				        <div class="swiper-slide">
				        	<%= image_tag @item.main_image, alt: @item.main_image.filename, class: 'img-fluid' %>
				        </div>

				        <% @item.images.each do |image| %>
				        	<div class="swiper-slide">
				        		<%= image_tag image, alt: image.filename, class: 'img-fluid' %>
				        	</div>
				        <% end %>
					    </div>

					    <div class="swiper-button-prev" style="color: lightgray;"></div>
			        <div class="swiper-button-next" style="color: lightgray;"></div>
						</div>
					<% else %>
						<%= image_tag @item.main_image, alt: @item.main_image.filename, class: "img-fluid" %>
					<% end %>
				<% end %>
			</div>

			<div class="col-12 col-lg-6">
				<div class="card border-0">
					<div class="card-body">
						<h2 class="card-title">
							<%= @item.name %>
						</h2>

						<h3 class="card-subtitle mt-2 text-success">
							<%= number_to_currency(@item.display_price) %>

							<small class="text-muted">
								per <%= @item.display_unit %>
							</small>
						</h3>

						<p class="card-text mt-3">
							<%= @item.description %>
						</p>

						<nav class="border-top mt-3 pt-3">
							<div class="nav nav-tabs" id="nav-tab" role="tablist">
								<% @item.units.sort_by(&:base_units).each do |unit| %>
									<%= link_to unit.name.pluralize.capitalize, "#tab_#{unit.name}", role: "tab", class: "item-tab-link nav-item nav-link #{unit.default? ? 'active' : ''}", data: { toggle: "tab" } %>
								<% end %>
						  </div>
						</nav>

						<div class="tab-content" id="nav-tabContent">
							<% @item.units.sort_by(&:base_units).each do |unit| %>
								<div 
									class="tab-pane fade <%= unit.default? ? 'show active' : '' %>"
									id="tab_<%= unit.name %>"
									role="tabpanel"
									data-controller="item"
									data-item-price="<%= unit.price %>"
									data-item-unit="<%= unit.name %>"
								>
									<%= simple_form_for CartItem.new(unit_id: unit.id), html: { class: "mt-3" }, remote: true do |f| %>
										<%= f.hidden_field :unit_id %>

										<%= f.input :quantity, label: "Quantity (#{unit.name.pluralize})", wrapper_html: { class: "mb-0" }, input_html: { id: "quantity_input_#{unit.name}" , data: { target: "item.input", action: "input->item#updateValues" } } %>

										<div class="mt-1" style="min-height: 19px;">
											<% unless unit.base? %>
												<small class="form-text text-muted mt-0">
													<%= t("unit.#{unit.name}", count: 1) +  " = " + t("unit.#{@item.base_unit.name}", count: unit.base_units) %>
												</small>
											<% end %>
										</div>

										<div class="row mt-3">
											<div class="col-6">
												<ul class="list-group list-group-flush">
													<li class="list-group-item" data-target="item.quantity">
														Chosen quantity
													</li>

													<li class="list-group-item" data-target="item.price">
														Price
													</li>
												</ul>
											</div>

											<div class="col-6 d-flex justify-content-end align-items-center">
												<%= f.submit "Add to cart", class: "btn btn-success btn-lg" %>
											</div>
										</div>
									<% end %>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal-footer mx-5">
	<div class="container-fluid text-center">
		<%= link_to "More product information", item_path(@item), class: "text-secondary text-decoration-none" %>
	</div>
</div>

app/views/items/autocomplete.html.erb
<% if @items.empty? %>
	<li class="list-group-item">
		No items found :(
	</li>
<% else %>
	<% @items.each do |item| %>
		<!-- onmousedown: "this.click() neccessary to beat the input blur event to the punch" -->
		<%= link_to item_path(item), class: "list-group-item text-decoration-none autocomplete-link", style: "height: 80px;", onmousedown: "this.click()" do %>
			<div class="d-flex align-items-center">
				<div class="d-flex align-items-center" style="height: 60px; width: 60px;">
					<% if item.main_image.attached? %>
						<%= image_tag item.main_image, class: 'img-fluid' %>
					<% end %>
				</div>

				<p class="mb-0 ml-4 text-secondary">
					<%= item.name %>
				</p>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/items/index.html.erb
<div class="container-lg">
	<div class="mr-3 mr-lg-0">
		<div class="input-group mt-4 mb-3 ml-auto" style="max-width: 400px; margin-right: -15px;">
		  <div class="input-group-prepend">
		    <label class="input-group-text" for="order_by_select"><%= t('.sort_by') %></label>
		  </div>

		  <select name="order" id="order_by_select" data-controller="select2 order" data-target="order.select">
		  	<%= options_for_select @order_options, params[:order] %>
		  </select>
		</div>
	</div>

	<div class="row bg-white pt-3 mb-0 mb-lg-5 pb-3" style="overflow-x: hidden;">
		<% unless @items.empty? %>
			<div class="col-12">
				<p class="float-right mr-3 text-muted">
					Showing <%= @item_count %> items
				</p>
			</div>

			<% @items.each do |item| %>
				<div class="col-6 col-lg-3 my-4">
					<%= render 'item', item: item %>
				</div>
			<% end %>

			<div class="col-12">
				<%= will_paginate @items, list_classes: %w(pagination justify-content-center) %>
			</div>
		<% else %>
			<h2 class="mx-auto">
				No items found
			</h2>
		<% end %>
	</div>
</div>

app/views/items/show.html.erb
<div class="container bg-white my-5" id="carts_show">
	<div class="row align-items-center">
		<div class="col-12 col-lg-6 text-center">
			<% if @item.image_count.positive? %>
				<% if @item.image_count > 1 %>
					<!-- Slider main container -->
					<div class="swiper-container" data-controller="swiper">
				    <!-- Additional required wrapper -->
				    <div class="swiper-wrapper align-items-center">
			        <!-- Slides -->
			        <div class="swiper-slide">
			        	<%= image_tag @item.main_image, alt: @item.main_image.filename, class: 'img-fluid' %>
			        </div>

			        <% @item.images.each do |image| %>
			        	<div class="swiper-slide">
			        		<%= image_tag image, alt: image.filename, class: 'img-fluid' %>
			        	</div>
			        <% end %>
				    </div>

				    <div class="swiper-button-prev" style="color: lightgray;"></div>
		        <div class="swiper-button-next" style="color: lightgray;"></div>
					</div>
				<% else %>
					<%= image_tag @item.main_image, alt: @item.main_image.filename, class: "img-fluid" %>
				<% end %>
			<% end %>
		</div>

		<div class="col-12 col-lg-6">
			<div class="card border-0">
				<div class="card-body">
					<h2 class="card-title">
						<%= @item.name %>
					</h2>

					<h3 class="card-subtitle mt-2 text-success">
						<%= number_to_currency(@item.display_price) %>

						<small class="text-muted">
							per <%= @item.display_unit %>
						</small>
					</h3>

					<p class="card-text mt-3">
						<%= @item.description %>
					</p>

					<nav class="border-top mt-3 pt-3">
						<div class="nav nav-tabs" id="nav-tab" role="tablist">
							<% @item.units.each do |unit| %>
								<%= link_to unit.name.pluralize.capitalize, "#tab_#{unit.name}", role: "tab", class: "item-tab-link nav-item nav-link #{unit.default? ? 'active' : ''}", data: { toggle: "tab" } %>
							<% end %>
					  </div>
					</nav>

					<div class="tab-content" id="nav-tabContent">
						<% @item.units.each do |unit| %>
							<div 
								class="tab-pane fade <%= unit.default? ? 'show active' : '' %>"
								id="tab_<%= unit.name %>"
								role="tabpanel"
								data-controller="item"
								data-item-price="<%= unit.price %>"
								data-item-unit="<%= unit.name %>"
								data-item-show="true"
							>
								<%= simple_form_for CartItem.new(unit_id: unit.id), html: { class: "mt-3" }, remote: true do |f| %>
									<%= f.hidden_field :unit_id %>

									<%= f.input :quantity, label: "Quantity (#{unit.name.pluralize})", wrapper_html: { class: "mb-0" }, input_html: { data: { target: "item.input", action: "input->item#updateValues" } } %>

									<div class="mt-1" style="min-height: 19px;">
										<% unless unit.base? %>
											<small class="form-text text-muted mt-0">
												<%= t("unit.#{unit.name}", count: 1) +  " = " + t("unit.#{@item.base_unit.name}", count: unit.base_units) %>
											</small>
										<% end %>
									</div>

									<div class="row mt-3">
										<div class="col-6">
											<ul class="list-group list-group-flush">
												<li class="list-group-item" data-target="item.quantity">
													Chosen quantity
												</li>

												<li class="list-group-item" data-target="item.price">
													Price
												</li>
											</ul>
										</div>

										<div class="col-6 d-flex justify-content-end align-items-center">
											<%= f.submit "Add to cart", class: "btn btn-success btn-lg" %>
										</div>
									</div>
								<% end %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row border-top pt-5">
		<div class="col-12 col-lg-6">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<h4>
						Product information
					</h4>
				</li>

				<li class="list-group-item py-3">
					<div class="row justify-content-between">
						<div class="col-6">
							<h5 class="font-weight-light mb-0">
								Ingredients
							</h5>
						</div>

						<div class="col-6">
							<p class="mb-0">
								Oatmeal 65%, cane sugar, coconut fat, grated coconut, rice extrudate (whole grain rice flour), sea salt
							</p>
						</div>
					</div>
				</li>

				<li class="list-group-item py-3">
					<div class="row justify-content-between">
						<div class="col-6">
							<h5 class="font-weight-light mb-0">
								Origin
							</h5>
						</div>

						<div class="col-6">
							<p class="mb-0">
								Ethiopia
							</p>
						</div>
					</div>
				</li>

				<li class="list-group-item py-3">
					<div class="row justify-content-between">
						<div class="col-6">
							<h5 class="font-weight-light mb-0">
								Organic control code
							</h5>
						</div>

						<div class="col-6">
							<p class="mb-0">
								DE-ÖKO-003
							</p>
						</div>
					</div>
				</li>
			</ul>
		</div>

		<div class="col-12 col-lg-6">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<h4>
						Average nutritional values per 100g
					</h4>
				</li>

				<li class="list-group-item">
					<table class="table table-striped">
						<tbody>
							<tr>
								<td>
									Energy
								</td>

								<td>
									2544 kJ / 608 kcal
								</td>
							</tr>

							<tr>
								<td>
									Fat
								</td>

								<td>
									51.6 g
								</td>
							</tr>

							<tr>
								<td>
									Carbohydrates
								</td>

								<td>
									11.6 g
								</td>
							</tr>

							<tr>
								<td>
									Protein
								</td>

								<td>
									20.0 g
								</td>
							</tr>

							<tr>
								<td>
									Salt
								</td>

								<td>
									0.030 g
								</td>
							</tr>
						</tbody>
					</table>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/items/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'show_modal') %>");
$("#modal-window").modal();