config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de/ do
    root to: 'items#index'

    # ActiveAdmin routes
    ActiveAdmin.routes(self)
    #

    # Sidekiq
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    #

    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

    # Simple resources
    resources :cart_items, only: [:create]
    resources :carts, only: [:edit, :update]
    resources :deliveries, only: [:edit, :update, :index, :show]
    #

    post "order_items/:id/add_to_cart", to: "order_items#add_to_cart", as: "add_to_cart_order_item"

    # Complex resources
    resources :recipes, only: [:index, :show, :new, :create] do
      collection do
        post ":id/toggle_like", to: "recipes#toggle_like", as: :toggle_like
        post ":id/add_to_cart", to: "recipes#add_to_cart", as: :add_to_cart
      end
    end

    resources :items, only: [:index, :show] do
      collection do
        get "autocomplete"
      end
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        get :receipt, action: :receipt
        post :add_to_cart, action: :add_to_cart
      end
    end
    #

    namespace :stripe do
      # stripe_event gem Engine
      mount StripeEvent::Engine, at: '/webhook', as: :event
      #

      get "payment_intents/:id/confirm", to: "payment_intents#confirm", as: :payment_intents_confirm
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :orders, only: [:show] do
          collection do
            post "breakdown"
          end
        end

        post "users/:id/update_driver_coordinates", to: "users#update_driver_coordinates", as: :update_driver_coordinates

        resources :deliveries, only: [:update]
        resources :cart_items, only: [:update, :destroy]
      end
    end
  end
end

app/views/layouts/_flashes.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success alert-dismissible fade show bottom-right mb-0" role="alert">
	  <%= flash[:notice] %>

	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger alert-dismissible fade show bottom-right mb-0" role="alert">
	  <%= flash[:alert] %>

	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="sticky-top bg-white" style="box-shadow: 0 1px 5px rgba(0,0,0,.16);">
	<div class="navbar navbar-light">
		<div class="navbar-brand px-lg-5 mr-0">
			<%= link_to "Less", root_path, class: "text-success font-weight-light text-decoration-none", style: "letter-spacing: 0.5rem;" %>
		</div>

		<div class="flex-grow-1 d-none d-lg-block" data-controller="autocomplete" data-autocomplete-url="<%= autocomplete_items_url %>">
			<%= form_tag items_path, method: :get, autocomplete: "off" do %>
				<div class="input-group w-100">
					<%= search_field_tag :search, params[:search], class: "form-control", placeholder: "What are you looking for?", id: "desktop_search_field", data: { target: 'autocomplete.input', action: "input->autocomplete#fetchResults blur->autocomplete#clearResults" } %>

					<div class="input-group-append">
						<button class="btn btn-outline-success" type="submit">
							<%= fa_icon "search" %>
						</button>
					</div>
				</div>
			<% end %>

			<ul class="list-group position-absolute" data-target="autocomplete.results" style="z-index: 10;"></ul>
		</div>

		<div class="navbar-expand">
			<ul class="navbar-nav ml-lg-3">
			  <li class="nav-item mr-3 my-auto">
			    <% if I18n.locale == :en %>
			    	<%= link_to url_for(locale: :de), class: 'nav-link px-0 py-0', style: "line-height: 0;" do %>
			    		<%= flag_icon :gb %>
			    	<% end %>
			    <% else %>
			    	<%= link_to url_for(locale: :en), class: 'nav-link px-0 py-0', style: "line-height: 0;" do %>
			    		<%= flag_icon :de %>
			    	<% end %>
			    <% end %>
			  </li>

			  <% if current_user %>
			  	<li class="nav-item dropdown">
			  	  <a class="dropdown-toggle btn btn-outline-success mr-2 mb-2 mb-lg-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  	    <%= t('.account') %>
			  	  </a>

			  	  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			  	  	<%= link_to t(".your_account"), edit_user_registration_path, class: "dropdown-item" %>
			  	  	<%= link_to t(".your_orders"), orders_path, class: "dropdown-item" %>
			  	  	<!-- <%= link_to "Your Recipes", recipes_path, class: "dropdown-item" %> -->
			  	    <div class="dropdown-divider"></div>
			  	    <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
			  	  </div>
			  	</li>
				<% else %>
					<li class="nav-item">
						<%= link_to "Log in", new_user_session_path, class: "btn btn-outline-secondary mr-2", style: "min-width: 80px;" %>
					</li>
			  <% end %>

			  <li class="nav-item">
			  	<%= link_to edit_cart_path(id: current_cart.id), remote: true, class: "btn btn-success position-relative", style: "min-width: 100px;"  do %>
			  		<%= fa_icon "shopping-cart" %>
			  		<%= t('.cart') %>
			  		<span class="badge badge-pill badge-danger" id="cart_count"><%= current_cart.count %></span>
			  	<% end %>
			  </li>
			</ul>
		</div>
	</div>

	<div class="px-3">
		<div class="flex-grow-1 d-block d-lg-none pb-3" data-controller="autocomplete" data-autocomplete-url="<%= autocomplete_items_url %>">
			<%= form_tag items_path, method: :get, autocomplete: "off" do %>
				<div class="input-group w-100">
					<%= search_field_tag :search, params[:search], class: "form-control", placeholder: "What are you looking for?", id: "mobile_search_field", data: { target: 'autocomplete.input', action: "input->autocomplete#fetchResults blur->autocomplete#clearResults" } %>

					<div class="input-group-append">
						<button class="btn btn-outline-success" type="submit">
							<%= fa_icon "search" %>
						</button>
					</div>
				</div>
			<% end %>

			<ul class="list-group position-absolute" data-target="autocomplete.results" style="z-index: 10;"></ul>
		</div>

		<ul class="nav nav-fill d-none d-lg-flex">
			<li class="nav-item">
				<%= link_to 'All Items', items_path, class: "nav-link pt-0 pb-1 #{@tags ? 'text-secondary' : 'text-success'}" %>
			</li>

			<% ['Meats', 'Cereals', 'Vegetables', 'Grains', 'Beverages', 'Personal Care'].each do |tag| %>
				<li class="nav-item">
					<%= link_to tag, items_path(request.query_parameters.except("page").deep_merge(filter: [tag] )), class: "nav-link pt-0 pb-1 text-secondary #{@tags.try(:include?, tag) ? 'text-success' : 'text-secondary'}" %>
				</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="bg-white" data-controller="sidebar">
  <div class="sidebar-content h-100">
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Less</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    
    <script src='https://js.stripe.com/v3/'></script> <!-- This should be changed as to not be included everywhere -->

    <%= favicon_link_tag asset_path('less_favicon.ico') %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashes' %>
    <%= render 'layouts/sidebar' %>
    
    <%= yield %>

    <!-- Modal -->
    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
        <div class="modal-content"></div>
      </div>
    </div>

    <%= javascript_tag do %>
      I18n.locale = "<%= I18n.locale %>";
      I18n.translations = <%= raw I18n::JS.filtered_translations.to_json %>;
    <% end %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title>PDF</title>
	</head>

	<body>
    <%= yield %>
	</body>
</html>